---
- hosts: appserver
  become: yes
  tasks:
  - name: Install Java 8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: Install tomcat
    yum:
      name: tomcat
      state: present
  - name: Download jenkins to webapps folder
    get_url:
      url: http://mirror.serverion.com/jenkins/war-stable/2.222.1/jenkins.war
      dest: /usr/share/tomcat/webapps
  - name: start tomcat service
    service:
      name: tomcat
      state: started
